jwt:
    secret: "secret"
spring:
    jpa:
        show-sql: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://localhost:3306/user_details"
        username: "root"
        password: "SuSundron007@"
server:
    port: 8081
